name: Accessibility Testing

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          echo 'installed'

      - name: Run accessibility tests
        run: |
           echo 'test run executed'
       # run: npx axe-cli --config axe-config.json --exit

      - name: Convert report to XML
        run: |
          npm install -g json2xml-cli
          json2xml-cli -i axe-results.json -t xml -o accessibility-report.xml

      - name: Upload accessibility report
        uses: actions/upload-artifact@v2
        with:
          name: Accessibility Report
          path: accessibility-report.xml
